In [1]:
#Q1

from collections import deque

class customer:
    name = "none"
    transaction = 0
    
    def __init__(self,name,transaction):
        self.name = name
        self.__transaction = transaction
        bank(self.name)

class bank:
    Customer_Queue = deque([])
    
    def __init__(self,name):
        self.name = name
        bank.Customer_Queue.append(self.name)
    
    def add_customer():
        new_customer = input("Enter customer's name: ")
        bank.Customer_Queue.append(new_customer)
        
        print("Customers in queue: ")
        print(bank.Customer_Queue)
    def serve_next_customer():
        bank.Customer_Queue.popleft()
        print("Customers in queue: ")
        print(bank.Customer_Queue)
    def isQueueEmpty():
        if(len(bank.Customer_Queue)==0):
            print("There are no customers left")
        
if __name__=="__main__":
    c1 = customer("ABC",5000)
    c2 = customer("DEF",7500)
    bank.add_customer()
    bank.serve_next_customer()
    bank.isQueueEmpty()
    bank.add_customer()
    bank.serve_next_customer()
    bank.serve_next_customer()
    bank.serve_next_customer()
    bank.isQueueEmpty()

Enter customer's name: AAA
Customers in queue: 
deque(['ABC', 'DEF', 'AAA'])
Customers in queue: 
deque(['DEF', 'AAA'])
Enter customer's name: ABDFEG
Customers in queue: 
deque(['DEF', 'AAA', 'ABDFEG'])
Customers in queue: 
deque(['AAA', 'ABDFEG'])
Customers in queue: 
deque(['ABDFEG'])
Customers in queue: 
deque([])
There are no customers left


In [23]:
#Q2

class Graph:
    def __init__(self,edges,n):
        self.adjList = [[] for _ in range(n)]
        
        for(src,dest) in edges:
            self.adjList[src].append(dest)
    
    def printGraph(graph):
        for src in range(len(graph.adjList)):
            for dest in graph.adjList[src]:
                print(f'({src}->{dest}',end='')
            print()

if __name__ == '__main__':
    edges =[(0,1),(1,2),(2,0),(2,1),(3,2),(4,5),(5,4)]
    n = 6
    graph = Graph(edges,n)
    
    printGraph(graph)

(0->1)
(1->2)
(2->0)(2->1)
(3->2)
(4->5)
(5->4)



In [24]:
#Q3

class Graph:
    
    def __init__(self, edges, n):
        self.adjList = [[] for _ in range(n)]
        
        for (src, dest, weight) in edges:
            self.adjList[src].append((dest, weight))

def printGraph(graph):
    for src in range(len(graph.adjList)):
        for (dest, weight) in graph.adjList[src]:
            print(f'({src} —> {dest}, {weight})',end = '')
        print()

if __name__ == '__main__':
    edges = [(0, 1, 6), (1, 2, 7), (2, 0, 5), (2, 1, 4), (3, 2, 10),
            (4, 5, 1), (5, 4, 3)]
    n = 6
    graph = Graph(edges, n)
    printGraph(graph)
 

(0 —> 1, 6)
(1 —> 2, 7)
(2 —> 0, 5)(2 —> 1, 4)
(3 —> 2, 10)
(4 —> 5, 1)
(5 —> 4, 3)


In [31]:
#Q4

class Vertex:
    def __init__(self, vertex):
        self.name = vertex
        self.neighbors = []
        
    def add_neighbor(self, neighbor):
        if isinstance(neighbor, Vertex):
            if neighbor.name not in self.neighbors:
                self.neighbors.append(neighbor.name)
                neighbor.neighbors.append(self.name)
                self.neighbors = sorted(self.neighbors)
                neighbor.neighbors = sorted(neighbor.neighbors)
        else:
            return False
        
    def add_neighbors(self, neighbors):
        for neighbor in neighbors:
            if isinstance(neighbor, Vertex):
                if neighbor.name not in self.neighbors:
                    self.neighbors.append(neighbor.name)
                    neighbor.neighbors.append(self.name)
                    self.neighbors = sorted(self.neighbors)
                    neighbor.neighbors = sorted(neighbor.neighbors)
            else:
                return False
        
    def __repr__(self):
        return str(self.neighbors)

class Graph:
    def __init__(self):
        self.vertices = {}
    
    def add_vertex(self, vertex):
        if isinstance(vertex, Vertex):
            self.vertices[vertex.name] = vertex.neighbors

            
    def add_vertices(self, vertices):
        for vertex in vertices:
            if isinstance(vertex, Vertex):
                self.vertices[vertex.name] = vertex.neighbors
            
    def add_edge(self, vertex_from, vertex_to):
        if isinstance(vertex_from, Vertex) and isinstance(vertex_to, Vertex):
            vertex_from.add_neighbor(vertex_to)
            if isinstance(vertex_from, Vertex) and isinstance(vertex_to, Vertex):
                self.vertices[vertex_from.name] = vertex_from.neighbors
                self.vertices[vertex_to.name] = vertex_to.neighbors
                
    def add_edges(self, edges):
        for edge in edges:
            self.add_edge(edge[0],edge[1])          
    
    def adjacencyList(self):
        if len(self.vertices) >= 1:
                return [str(key) + ":" + str(self.vertices[key]) for key in self.vertices.keys()]  
        else:
            return dict()
        
    def adjacencyMatrix(self):
        if len(self.vertices) >= 1:
            self.vertex_names = sorted(g.vertices.keys())
            self.vertex_indices = dict(zip(self.vertex_names, range(len(self.vertex_names)))) 
            import numpy as np
            self.adjacency_matrix = np.zeros(shape=(len(self.vertices),len(self.vertices)))
            for i in range(len(self.vertex_names)):
                for j in range(i, len(self.vertices)):
                    for el in g.vertices[self.vertex_names[i]]:
                        j = g.vertex_indices[el]
                        self.adjacency_matrix[i,j] = 1
            return self.adjacency_matrix
        else:
            return dict()              
                        
def graph(g):
    return str(g.adjacencyList()) + '\n' + '\n' + str(g.adjacencyMatrix())


a = Vertex('A')
b = Vertex('B')
c = Vertex('C')
d = Vertex('D')
e = Vertex('E')

a.add_neighbors([b,c,e]) 
b.add_neighbors([a,c])
c.add_neighbors([b,d,a,e])
d.add_neighbor(c)
e.add_neighbors([a,c])
        
g = Graph()
print(graph(g))
print()
g.add_vertices([a,b,c,d,e])
g.add_edge(b,d)
print(graph(g))

{}

{}

["A:['B', 'C', 'E']", "B:['A', 'C', 'D']", "C:['A', 'B', 'D', 'E']", "D:['B', 'C']", "E:['A', 'C']"]

[[0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]
